language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t balyan19/docker-react -f Dockerfile.dev .

script:
  - docker run balyan19/docker-react npm run test -- --coverage
